name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        scala: [2.13.14]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@32ffa16635ff8f19cc21ea253a987f0fdf29844c
        with:
          java-version: adopt@1.11

      - name: Cache sbt
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier/cache/v1
            ~/.cache/coursier/v1
          key: sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

      - name: Build project
        run: sbt ++${{ matrix.scala }} test
