name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        scala: [2.13.16]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Java and Scala
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # 4.7.1
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "sbt"

      - name: Build project
        run: sbt ++${{ matrix.scala }} test
